language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - mysql -e 'CREATE DATABASE test;';
  - psql -U postgres -c 'CREATE DATABASE test;';

install: composer install

services:
  - mysql
  - postgresql

matrix:
  allow_failures:
    - php: hhvm
  exclude:
    - php: hhvm
      env: DB=pgsql  # PDO driver for pgsql is unsupported by HHVM (3rd party install for support)